set -g history-limit 9999999
set -g prefix C-z # Set prefix from C-b to C-a
unbind C-b # Release the C-b binding from its default prefix role
bind r source-file ~/.tmux.conf \; display ​"Reloaded!" # reload config on C-z r


bind | split-window -h # split to side-by-side panes on C-z |
bind - split-window -v # split to vertically-stacked panes on C-z -

# Enable mouse support
# set -g mouse on

# set the status line's colors
set -g status-style fg=white,bg=blue
