set -g history-limit 9999999
set -g prefix C-z # Set prefix from C-b to C-z
unbind C-b # Release the C-b binding from its default prefix role
bind r source-file ~/.tmux.conf \; display ​"Reloaded!" # reload config on C-z r


bind | split-window -h # split to side-by-side panes on C-z |
bind - split-window -v # split to vertically-stacked panes on C-z -

# Enable mouse support
# set -g mouse on

# set the status line's colors
set -g status-style fg=white,bg=blue

# Use 256 colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Faster key repetition
set -s escape-time 0

# Quick save buffer to file (useful for extracting from recordings)
bind S command-prompt -p "Save buffer to:" "capture-pane -S -1000000; save-buffer %1"

# Prevent accidentally suspending `tmux attach`
unbind C-z